### ISSUE TITLE
ARTS vector arithmetic is broken

### ISSUE THREAD

**Issue by simonpf** [atmtools/arts#584] opened 2022-12-22 17:11 UTC
**Scaling a vector with a scalar leads to unexpected results.**

When attempting to scale a vector by a scalar, the scalar is implicitly casted to a ``ConstVectorView`` 
and the result is then the dot product of the original vector and the on-the-fly-created Vector stump.

**To Reproduce**
````c++
#include "matpackI.h"
#include <iostream>

int main(int argc, const char ** argv) {

    Vector a = Vector(10, 2.0);
    std::cout <<  2.0 * a  << std::endl;
}
````

This prints

````
4
````
because the output is single scalar corresponding to the product of the first element of ``a`` and ``2.0``.

**Expected behavior**

The result should be a vector of length 10 containing the value ``4``.
````
4   4   4   4   4   4   4   4   4   4
````

**Comment by riclarsson** [comment] 2023-01-05 11:22
I agree it is broken.  It cannot be fixed without major restructuring because almost all constructors are implicit by design to make the core idea of having these inheritances in `matpack` work.

There is an easy workaround to make that work though.

If you add `#include "matpack_eigen.h"` at the top of your file, the expected behavior is reproduced.  Mostly that is, you will have a lazy Eigen-vector and not an ARTS vector so you have to be careful to convert back between them somehow (note that `matpack::as_eigen(out_vec).noalias()` can be used to make this memory-easy).

**Comment by riclarsson** [comment] 2023-02-08 12:03
Solved with new mdspan

**Closed by riclarsson** 2023-02-08 12:03 UTC
Labels: bug
