### ISSUE TITLE
aa_grid

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#521] opened 2022-09-10 09:30 UTC
Bug: If you set aa_grid = [] you get an assert error. At least in DisortCalcWithARTSSurface, but I assume this is also true for the other Disort methods. There should be a check somewhere. And the demand on aa_grid should be clear in built-in doc.

That said, I think aa_grid=[] is the correct choice for 1D. I think there was a discussion about this. But it was during my holiday (?) and I did not have time/energy to follow the discussion. Seems that the decision was that aa_grid shall have length 1 for 1D. This is inconsistent with how we treat lat_grid and lon_grid. To say that unused grids shall be empty makes the coding more tedious, but is more clear for the user. If length 1, what is the value saying? Is the value considered or not? That is, my opinion is that aa_grid shall be empty for 1D.

For clarity, I consider the p, lat, lon, za and aa grids as basic ones. The radiation in the atmosphere can vary in all these dimensions (together with frequency and stokes). There could be others, less used, grids where we demand length 1 when not used, but that feels less critical.

**Comment by olemke** [comment] 2022-09-14 08:50
@erikssonpatrick The convention that `aa_grid` must have a length of 1 for the 1-D case is not a bug, but has been there for a long time. There is an explicit check in [`DOAngularGridsSet`](https://github.com/atmtools/arts/blob/900c10c364eb64dfcfa7b7eb761ab1f1c1ac4337/src/m_doit.cc#L87) This has been there at least since 2016 when Jana introduced that method.

**Comment by m-brath** [comment] 2022-09-14 09:40
I agree that aa_grid=[] would be the correct choice for 1D, but only for thermal radiation and DISORT. For the DOIT you must have an aa_grid of size greater than 0 even for 1D atmosphere. Furthermore, if you have a direct source, aa_grid must be greater than 0 even for 1D atmospheres in Disort. But I can add a check in the DisortCalc-methods, that the size of aa_grid must be greater than 0.

**Comment by riclarsson** [comment] 2022-09-20 11:50
I agree with the idea of simpler interfaces, but I don't know what I can do about this.  It seems like an internal Disort-interaction change.  So I remove myself from this.

**Comment by olemke** [comment] 2022-09-28 13:12
Closing this for now. Needs to be revisited later with a larger scale refactoring of how all angular grids work.

**Closed by olemke** 2022-09-28 13:12 UTC
