### ISSUE TITLE
NANs in absorption crosssections for H2O lower frequencies with Voigt lineshape

### ISSUE THREAD

**Issue by olemke** [atmtools/arts#293] opened 2021-01-22 13:20 UTC
For the example described below, the Faddeeva function returns INF values for a handful of H2O lines from the 172 and 182 isotopologues for frequencies below ~1.7 GHz in `f_grid` (also depends on pressure). Eventually, these values lead to NANs in the absorption crosssections.

**To Reproduce**
A branch with an example controlfile and debug code is available at:
https://github.com/olemke/arts/tree/debug-voigt-inf

The branch can be checked out into a new directory if needed with:
`git clone -b debug-voigt-inf https://github.com/olemke/arts.git arts-debug-inf`

The example controlfile is located at `controlfiles/debug-voigt-inf/debugvoitinf.arts`
 
Debug code was added to [`Linefunctions::set_voigt`](https://github.com/olemke/arts/blob/c3822bd21a17ec3ad19efdcc3d7eca0684ff6c37/src/linefunctions.cc#L345) to output the indexes of F that contain INFs and the band species.

Output looks like this (just one failed line as an example):

```
 ➜ ../../build/src/arts -r020 -n1 debugvoitinf.arts
[snip]
0@1 1@1.0101 2@1.0202 3@1.0303 4@1.0404 5@1.0505 6@1.0606 7@1.0707
^^^ Indexes and frequencies [Ghz] in f_grid of INF values
F0 of failed line: 42420632.807
Species of failed line: H2O-172
[snip]
Run-time error in controlfile: debugvoitinf.arts
Run-time error in method: yCalc
One or several NaNs found in *y*.
Stopping ARTS execution.
Goodbye.
```

Other lineshapes than Voigt do not experience this issue.

**Expected behavior**
Lineshape function should not return INF values.

**System info:**
 - OS: macOS/Linux, GCC 10/Clang 11

**Comment by riclarsson** [comment] 2021-01-22 14:04
Ok, I can build and I can reproduce the error.

This one is tricky.  You claim that you need negative central frequencies of the lines at some high pressure.  This creates the issue that the `G0`-part of `z` becomes negative, which I think is the main problem here because that's a function that grows very quickly when `z.imag()` gets more negative.

A temporary solution is otherwise to do "const Numeric invGD = std::abs(1.0 / GD);", but I am not sure if this will end up creating issues with the Mirroring-routines...

A more permanent solution must be found.  You should probably just use Lorentz as line shape at these frequencies anyways.  With the absolutely required normalization factors, that will allow you to be somewhat close to Debye, which is the name of the line shape that you sort of want to emulate.  (Note, I did not try using Lorentz yet, but it should be more stable.)

I am not sure what the solution should be going into ARTS.  I think that `lbl_checkedCalc` maybe should be modified to not allow Voigt when the central frequencies are so small that they will be shifted negatively at the highest pressure/temperatures.  But this is a very expensive check.  Maybe if the Lorentz line shape works, set_voigt should just use Voigt when `F0` is negative?

**Comment by riclarsson** [comment] 2021-01-22 15:02
Here is the suggested solution that involves the least number of changes in code:

```cpp
void Linefunctions::set_voigt(
    Eigen::Ref<Eigen::VectorXcd> F,
    Eigen::Ref<Eigen::MatrixXcd> dF,
    Eigen::Ref<Eigen::Matrix<Complex, Eigen::Dynamic, ExpectedDataSize()>> data,
    const Eigen::Ref<const Eigen::VectorXd> f_grid,
    const Numeric& zeeman_df,
    const Numeric& magnetic_magnitude,
    const Numeric& F0_noshift,
    const Numeric& GD_div_F0,
    const LineShape::Output& lso,
    const AbsorptionLines& band,
    const Index& line_ind,
    const ArrayOfRetrievalQuantity& derivatives_data,
    const ArrayOfIndex& derivatives_data_position,
    const Numeric& dGD_div_F0_dT,
    const LineShape::Output& dT,
    const LineShape::Output& dVMR) {
  constexpr Complex iz(0.0, 1.0);

  // Size of problem
  auto nppd = derivatives_data_position.nelem();

  // Doppler broadening and line center
  const Numeric F0 = F0_noshift + zeeman_df * magnetic_magnitude + lso.D0 + lso.DV;
  
  /* Use Lorentz if the shifted line center has a 
   * different sign than the original line center */
  if (std::signbit(F0) not_eq std::signbit(F0_noshift)) {
    set_lorentz(F,
                dF,
                data,
                f_grid,
                zeeman_df,
                magnetic_magnitude,
                F0_noshift,
                lso, band,
                line_ind,
                derivatives_data,
                derivatives_data_position,
                dT,
                dVMR);
  } else {
    const Numeric GD = GD_div_F0 * F0;
    const Numeric invGD = 1.0 / GD;
    const Numeric dGD_dT = dGD_div_F0_dT * F0 - GD_div_F0 * (dT.D0 + dT.DV);

    // constant normalization factor for Voigt
    const Numeric fac = Constant::inv_sqrt_pi * invGD;

    // Naming req data blocks
    auto z = data.col(0);
    auto dw = data.col(1);

    // Frequency grid
    z.noalias() = invGD * (Complex(-F0, lso.G0) + f_grid.array()).matrix();

    // Line shape
    F.noalias() = fac * z.unaryExpr(&w);

    if (nppd) {
      dw.noalias() = 2 * (Complex(0, fac * Constant::inv_sqrt_pi) -
                          z.cwiseProduct(F).array())
                            .matrix();

      for (auto iq = 0; iq < nppd; iq++) {
        const auto& deriv = derivatives_data[derivatives_data_position[iq]];

        if (is_frequency_parameter(deriv))
          dF.col(iq).noalias() = invGD * dw;
        else if (deriv == Jacobian::Atm::Temperature)
          dF.col(iq).noalias() =
              dw * Complex(-dT.D0 - dT.DV, dT.G0) * invGD -
              F * dGD_dT * invGD - dw.cwiseProduct(z) * dGD_dT * invGD;
        else if ((deriv == Jacobian::Line::Center or
                  is_pressure_broadening_DV(deriv)) and
                Absorption::id_in_line(band, deriv.QuantumIdentity(), line_ind))
          dF.col(iq).noalias() = -F / F0 - dw * invGD - dw.cwiseProduct(z) / F0;
        else if (is_pressure_broadening_G0(deriv) and
                Absorption::id_in_line(band, deriv.QuantumIdentity(), line_ind))
          dF.col(iq).noalias() = iz * dw * invGD;
        else if (is_pressure_broadening_D0(deriv) and
                Absorption::id_in_line(band, deriv.QuantumIdentity(), line_ind))
          dF.col(iq).noalias() = -dw * invGD;
        else if (is_magnetic_parameter(deriv))
          dF.col(iq).noalias() = dw * (-zeeman_df * invGD);
        else if (deriv == Jacobian::Line::VMR and
                Absorption::id_in_line(band, deriv.QuantumIdentity(), line_ind))
          dF.col(iq).noalias() =
              dw * Complex(-dVMR.D0 - dVMR.DV, dVMR.G0) * invGD;
        else
          dF.col(iq).setZero();
      }
    }
  }
}
```

Note that this will require an update in the documentation.

**Comment by olemke** [comment] 2021-02-05 07:58
Thanks @riclarsson . Your proposed solution does indeed fix the issue.

**Comment by riclarsson** [comment] 2021-02-05 11:04
@stefanbuehler and @olemke 

I am partly against my own solution.  You are running ARTS with bad numbers.  In short the error: you are shifting the line center from positive to negative values.  You are running with negative frequency for a line which is not mirrored.

The Lorentz solution just works around the physical issue of bad input.  If that's good enough, then do use this implementation.  I think it is a bad idea.  I think instead and/or in addition, one of several things should happen:

1)  lbl_checkedCalc should catch the possibility of negative absorption and suggest that these lines/bands are forced to use another line shape.  I am suspecting the physical output near zero of these lines to anyways be quite bad.

2)  HITRAN should be notified so that we can check with them if the values are indeed incorrect.  Shifting to almost 2 GHz lower frequency seems bad (though to be fair, HITRAN is using T0 pressure shift [I think] whereas we have said that they should be using T5 in legacy ARTS and are therefore using it today, so this might be our fault entirely.  At least perhaps this should be checked before claiming too many things to HITRAN folks.)

3)  The VoigtLorentz line shape should be added to ARTS with some simple equation that when pressure broadening is, say, 100 times that of Doppler broadening at some fixed inputs, the Lorentz line shape is used instead of Voigt.

Note that I am actively trying to get rid of all error handling in Linefunctions, so I don't want the error handling there.  This is very sensitive code where a lot of stuff can go wrong so it should not allow any errors to go into it, so that it can assume there's no errors at all.  I am still struggling with this...

**Comment by olemke** [comment] 2021-05-10 13:14
@riclarsson Can this be closed or is there anything left to do?

**Comment by riclarsson** [comment] 2021-06-11 14:11
Is this still open?

**Comment by stefanbuehler** [comment] 2021-06-12 11:32
I don't understand. Does the numerical error occur when the shift is by 0Hz (that would be unacceptable)?

Or if the shifted line by accident lands on exactly 0 Hz?

**Comment by riclarsson** [comment] 2021-06-13 09:20
The latter.

I've explicitly disallowed line centers at 0 Hz, so it shouldn't happen that easily now.  (If they are needed, something special has to happen anyways, so a special option is required.)

**Comment by stefanbuehler** [comment] 2021-06-13 09:42
Ok.

**Closed** 2022-05-25 09:48 UTC
Labels: bug
